#!/usr/bin/env perl

use Git;
my $repo = Git->repository (Directory => '.');

my @modified_files = $repo->command('diff', "--name-only", "HEAD", "HEAD^");

die("No Dockerfile or cpanfile modified in the last commit\n")  unless grep( /Dockerfile|cpanfile/, @modified_files);
