name: "Tests module"
on: [push,pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install modules by apt
        run: sudo apt-get install cpanminus
      - name: Prepare for tests
        run: sudo cpanm --installdeps .
      - name: Perform tests
        run: prove -l
