name: "Tests module"
on: [push,pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Prepare for tests
        run: |
          cpanm --installdeps .
      - name: Perform tests
        run: prove
